plugins {
    id("quarkus_setting")
}


dependencies {
    
    // REST エンドポイント用 (JAX-RS) 
    implementation 'io.quarkus:quarkus-rest'
    
    // JSONパース・バインディング用 (Jackson)
    implementation 'io.quarkus:quarkus-rest-jackson'
    
    // 外部API取得用 HTTPクライアント
    implementation 'io.quarkus:quarkus-rest-client-jackson'

    // Azure Function
    implementation 'io.quarkus:quarkus-azure-functions-http'

    // LINE Bot Sdk Model
    implementation("com.linecorp.bot:line-bot-model:6.0.0")
    
    // LINE Bot Sdk Parser
    implementation("com.linecorp.bot:line-bot-parser:6.0.0")
}
