	
# quarkus.http.root-path=/api
# quarkus.http.port=${FUNCTIONS_CUSTOMHANDLER_PORT:8080}

quarkus.azure-functions.app-name=Quarkus-Sample
quarkus.azure-functions.app-service-plan-name=EastUSLinuxDynamicPlan
quarkus.azure-functions.resource-group=find-anime-detail
quarkus.azure-functions.region=japaneast
quarkus.azure-functions.runtime.java-version=25


quarkus.native.enabled=true
quarkus.package.jar.enabled=false
